version: '3'
services:
  server:
    container_name: jonkofee-profile-server
    image: keymetrics/pm2:latest-alpine
    ports:
      - ${NODE_SERVER_PORT}:8080
    volumes:
      - ./:/app
    working_dir: /app