version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NODE_SERVER_PORT}:80
      - 443:443
    volumes:
      - ./public:/srv/www/public
      - ./dist:/srv/www/dist
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/cert:/srv/www/cert
    depends_on:
      - nodejs

  nodejs:
    container_name: jonkofee-profile-server
    image: keymetrics/pm2:latest-alpine
    expose:
      - "8080"
    volumes:
      - ./:/app
    working_dir: /app